on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: ssh and deploy
    runs-on: ubuntu-latest
    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and deploy
        run: ssh root@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout main && git pull && docker-compose up --build -d && exit"
      - name: clean
        run: rm -rf ~/.ssh
